# =========================
# ROOT LOGGER
# =========================
rootLogger.level=DEBUG

rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.console.level = INFO

rootLogger.appenderRef.file.ref = FileAppender
rootLogger.appenderRef.file.level = DEBUG


# =========================
# CONSOLE APPENDER
# =========================

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.target = SYSTEM_OUT

appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d %p %c - %m%n


# =========================
# FILE APPENDER
# =========================

appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = logs/debug.log
appender.file.append = false

appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d %p %c - %m%n